[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
NEXT_CACHE_DISABLED = "1"
NEXT_BUILD_CACHE_DISABLED = "1"
NEXT_CLEAR_CACHE = "1" 